version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify --ssl --sslcert /run/secrets/portainer.cosmicsystem.id.cer --sslkey /run/secrets/portainer.cosmicsystem.id.key
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /home/sysop/portainer_data:/data
    networks:
      - portainer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    secrets:
        - portainer.cosmicsystem.id.cer
        - portainer.cosmicsystem.id.key

networks:
  portainer:
    driver: overlay
    attachable: true

secrets:
  portainer.cosmicsystem.id.cer:
    external: true
  portainer.cosmicsystem.id.key:
    external: true

volumes:
  portainer_data:
